from .smoothness import smoothness_loss, smoothness_loss_dr
from .total_variation import total_variation_loss, total_variation_loss_dr
from .global_sharing import global_sharing, global_sharing_dr, compute_global_sharing_inputs